### ISSUE TITLE
python pointnet2/lib/setup.py install

### ISSUE THREAD

**Issue by yangyang117** [uncbiag/robot#2]
Thank you for your excellent work. when i using the code, there are some errors.
first  i use ubuntu,cuda11.3,pytorch1.8, it shows :

```
/home/lh/Nasdata/DJstudents/yyang17/Code/robot/pointnet2/lib/src/ball_query.cpp:3:10: fatal error: THC/THC.h: 没有那个文件或目录
    3 | #include <THC/THC.h>

```

In order to solve this , i tried to use cuda10.2, pytorch1.6,but there still has some errors:
```

  _File "/home/lh/anaconda3/envs/yy_mesh_1/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
    cmd_obj.run()
  File "/home/lh/anaconda3/envs/yy_mesh_1/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/home/lh/anaconda3/envs/yy_mesh_1/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 346, in run
    self.build_extensions()
  File "/home/lh/anaconda3/envs/yy_mesh_1/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 653, in build_extensions
    build_ext.build_extensions(self)
  File "/home/lh/anaconda3/envs/yy_mesh_1/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 466, in build_extensions
    self._build_extensions_serial()
  File "/home/lh/anaconda3/envs/yy_mesh_1/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 492, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/lh/anaconda3/envs/yy_mesh_1/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 202, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/lh/anaconda3/envs/yy_mesh_1/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 547, in build_extension
    objects = self.compiler.compile(
  File "/home/lh/anaconda3/envs/yy_mesh_1/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 473, in unix_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "/home/lh/anaconda3/envs/yy_mesh_1/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1233, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "/home/lh/anaconda3/envs/yy_mesh_1/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1538, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension_
```

Can you share your version of pytorch, cuda & pykeops( I used version of 1.5, 2.1 also come out errors)

**Comment by yangyang117** [comment]
When I fixed the ninja and nvcc problems, there are new errors.

```
g++: error: /home/lh/Nasdata/DJstudents/yyang17/Project_remesh/robot/build/temp.linux-x86_64-cpython-38/src/ball_query.o: 没有那个文件或目录
g++: error: /home/lh/Nasdata/DJstudents/yyang17/Project_remesh/robot/build/temp.linux-x86_64-cpython-38/src/ball_query_gpu.o: 没有那个文件或目录
g++: error: /home/lh/Nasdata/DJstudents/yyang17/Project_remesh/robot/build/temp.linux-x86_64-cpython-38/src/group_points.o: 没有那个文件或目录
g++: error: /home/lh/Nasdata/DJstudents/yyang17/Project_remesh/robot/build/temp.linux-x86_64-cpython-38/src/group_points_gpu.o: 没有那个文件或目录
g++: error: /home/lh/Nasdata/DJstudents/yyang17/Project_remesh/robot/build/temp.linux-x86_64-cpython-38/src/interpolate.o: 没有那个文件或目录
g++: error: /home/lh/Nasdata/DJstudents/yyang17/Project_remesh/robot/build/temp.linux-x86_64-cpython-38/src/interpolate_gpu.o: 没有那个文件或目录
g++: error: /home/lh/Nasdata/DJstudents/yyang17/Project_remesh/robot/build/temp.linux-x86_64-cpython-38/src/pointnet2_api.o: 没有那个文件或目录
g++: error: /home/lh/Nasdata/DJstudents/yyang17/Project_remesh/robot/build/temp.linux-x86_64-cpython-38/src/sampling.o: 没有那个文件或目录
g++: error: /home/lh/Nasdata/DJstudents/yyang17/Project_remesh/robot/build/temp.linux-x86_64-cpython-38/src/sampling_gpu.o: 没有那个文件或目录
error: command '/usr/bin/g++' failed with exit code 1
```

**In the win(win10+cuda11.0+pytorch1.7.0) & ubuntu(ubuntu+cuda11.0+pytorch1.7.0),this error happend in either platform.**

The whole message:
**```
install
running install
/home/lh/anaconda3/envs/yy_mesh/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/home/lh/anaconda3/envs/yy_mesh/lib/python3.8/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running bdist_egg
running egg_info
writing pointnet2.egg-info/PKG-INFO
writing dependency_links to pointnet2.egg-info/dependency_links.txt
writing top-level names to pointnet2.egg-info/top_level.txt
reading manifest file 'pointnet2.egg-info/SOURCES.txt'
writing manifest file 'pointnet2.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
building 'pointnet2_cuda' extension
Emitting ninja build file /home/lh/Nasdata/DJstudents/yyang17/Project_remesh/robot/build/temp.linux-x86_64-cpython-38/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
1.10.2
creating build/lib.linux-x86_64-cpython-38
g++ -pthread -B /home/lh/anaconda3/envs/yy_mesh/compiler_compat -Wl,--sysroot=/ -pthread -shared -B /home/lh/anaconda3/envs/yy_mesh/compiler_compat -L/home/lh/anaconda3/envs/yy_mesh/lib -Wl,-rpath=/home/lh/anaconda3/envs/yy_mesh/lib -Wl,--no-as-needed -Wl,--sysroot=/ /home/lh/Nasdata/DJstudents/yyang17/Project_remesh/robot/build/temp.linux-x86_64-cpython-38/src/ball_query.o /home/lh/Nasdata/DJstudents/yyang17/Project_remesh/robot/build/temp.linux-x86_64-cpython-38/src/ball_query_gpu.o /home/lh/Nasdata/DJstudents/yyang17/Project_remesh/robot/build/temp.linux-x86_64-cpython-38/src/group_points.o /home/lh/Nasdata/DJstudents/yyang17/Project_remesh/robot/build/temp.linux-x86_64-cpython-38/src/group_points_gpu.o /home/lh/Nasdata/DJstudents/yyang17/Project_remesh/robot/build/temp.linux-x86_64-cpython-38/src/interpolate.o /home/lh/Nasdata/DJstudents/yyang17/Project_remesh/robot/build/temp.linux-x86_64-cpython-38/src/interpolate_gpu.o /home/lh/Nasdata/DJstudents/yyang17/Project_remesh/robot/build/temp.linux-x86_64-cpython-38/src/pointnet2_api.o /home/lh/Nasdata/DJstudents/yyang17/Project_remesh/robot/build/temp.linux-x86_64-cpython-38/src/sampling.o /home/lh/Nasdata/DJstudents/yyang17/Project_remesh/robot/build/temp.linux-x86_64-cpython-38/src/sampling_gpu.o -L/home/lh/anaconda3/envs/yy_mesh/lib/python3.8/site-packages/torch/lib -L/usr/local/cuda/lib64 -lc10 -ltorch -ltorch_cpu -ltorch_python -lcudart -lc10_cuda -ltorch_cuda -o build/lib.linux-x86_64-cpython-38/pointnet2_cuda.cpython-38-x86_64-linux-gnu.so
g++: error: /home/lh/Nasdata/DJstudents/yyang17/Project_remesh/robot/build/temp.linux-x86_64-cpython-38/src/ball_query.o: 没有那个文件或目录
g++: error: /home/lh/Nasdata/DJstudents/yyang17/Project_remesh/robot/build/temp.linux-x86_64-cpython-38/src/ball_query_gpu.o: 没有那个文件或目录
g++: error: /home/lh/Nasdata/DJstudents/yyang17/Project_remesh/robot/build/temp.linux-x86_64-cpython-38/src/group_points.o: 没有那个文件或目录
g++: error: /home/lh/Nasdata/DJstudents/yyang17/Project_remesh/robot/build/temp.linux-x86_64-cpython-38/src/group_points_gpu.o: 没有那个文件或目录
g++: error: /home/lh/Nasdata/DJstudents/yyang17/Project_remesh/robot/build/temp.linux-x86_64-cpython-38/src/interpolate.o: 没有那个文件或目录
g++: error: /home/lh/Nasdata/DJstudents/yyang17/Project_remesh/robot/build/temp.linux-x86_64-cpython-38/src/interpolate_gpu.o: 没有那个文件或目录
g++: error: /home/lh/Nasdata/DJstudents/yyang17/Project_remesh/robot/build/temp.linux-x86_64-cpython-38/src/pointnet2_api.o: 没有那个文件或目录
g++: error: /home/lh/Nasdata/DJstudents/yyang17/Project_remesh/robot/build/temp.linux-x86_64-cpython-38/src/sampling.o: 没有那个文件或目录
g++: error: /home/lh/Nasdata/DJstudents/yyang17/Project_remesh/robot/build/temp.linux-x86_64-cpython-38/src/sampling_gpu.o: 没有那个文件或目录
error: command '/usr/bin/g++' failed with exit code 1
```**

**Comment by hbgtjxzbbx** [comment]
Hi thanks for your interests.  
This pointnet2 lib is borrowed from third party and seems to be out of maintenance.  Please check your gcc version is not too new, and make sure the nvcc  and pytorch are of the same version.
This may help:
https://lightrun.com/answers/facebookresearch-votenet-unable-to-compile-pointnet2

Besides, please use this code on linux as keops doesn't support windows.

**Comment by yangyang117** [comment]
> 

thank you for your answer. I have solved this problem.

use default pytorch (do not need to chage the nvcc -v), and use the 
https://github.com/facebookresearch/votenet
pointnet2; the use the https://lightrun.com/answers/facebookresearch-votenet-unable-to-compile-pointnet2 answer. 

thank you very much.
