### ISSUE TITLE
Translation between DIRLab and PVT coordinates

### ISSUE THREAD

**Issue by alexbgl** [uncbiag/robot#5]
Hi @hbgtjxzbbx 
thank you for sharing the code for your great work!

Could you please guide me on how to precisely transform the DIRLab landmarks to the coordinate system of the PVT clouds or the other way round?

Thanks!

**Comment by hbgtjxzbbx** [comment]
Thanks for your interests. The code is in lung preprocessing script. 
https://github.com/uncbiag/robot/blob/c42cb4ce770c9d5f210eeeac28257656650daade/robot/experiments/datasets/lung/dirlab_processing.py#L197
